name: yele
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # // Cupertino Icons // #
  cupertino_icons: ^1.0.8

  # // Dependency Injection // #
  get_it: ^8.0.3

  # // Check Network Connectivity // #
  connectivity_plus: ^6.1.3

  # // Responsive UI // #
  sizer: ^3.0.5

  # // Default Splash Screen // #
  flutter_native_splash: ^2.4.5

  # // State Management // #
  get: ^4.7.2
  pin_code_fields: ^8.0.1
  file_picker: ^10.0.0
  path: ^1.9.1
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  device_info_plus: ^11.3.3
  geolocator: ^13.0.4
  dio: ^5.8.0+1
  hive_flutter: ^1.1.0
  http_parser: ^4.1.2
  carousel_slider: ^5.0.0
  dropdown_button2: ^2.3.9
  flutter_masonry_view: ^0.0.2
  flutter_staggered_grid_view: ^0.7.0
  dashboard: ^0.0.4
  dots_indicator: ^4.0.1
  lazy_load_scrollview: ^1.3.0
  loading_animation_widget: ^1.3.0
  table_calendar: ^3.2.0
  intl: ^0.20.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_assets:
  assets_path: assets/
  output_path: lib/src/config/constants
  filename: assets.dart

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/flags/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/opensans/OpenSans-Bold.ttf
        - asset: assets/fonts/opensans/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/opensans/OpenSans-Light.ttf
        - asset: assets/fonts/opensans/OpenSans-Medium.ttf
        - asset: assets/fonts/opensans/OpenSans-Regular.ttf
        - asset: assets/fonts/opensans/OpenSans-SemiBold.ttf

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#3FA9F5"
  image: "assets/images/512_512.png"

  android_12:
    color: "#3FA9F5"
    image: "assets/images/1152_1152.png"